server:
  port: 3333   # HTTP (Tomcat) port
  
spring:
  application:
     name: web-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    preferIpAddress: true


---
spring:
  profiles: docker
  application:
     name: web-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://registry-container:1111/eureka/
  instance:
    preferIpAddress: true

