version: '3'

services:
  registry-container:
    image: springdemo/registry
    ports:
      - "1111:1111"

  mysql-docker-container:
    image: mysql:latest
    container_name: book-docker-sql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ebookshop
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=xxxx
    volumes:
      - /data/mysql
      
  book-service-container:
    image: springdemo/book-service
    depends_on:
      - mysql-docker-container
      - registry-container
    ports:
      - "2222:2222"
    
  web-service-container:
    image: springdemo/web-service
    depends_on:
      - book-service-container
      - registry-container
    ports:
      - "3333:3333"
  
  gateway-container:
    image: springdemo/gateway
    depends_on:
      - registry-container
    ports:
      - "4444:4444"
      
      