version: '3'

services:
  registry-container:
    image: springdemo/registry
    build: registry
    ports:
      - "1111:1111"

  mysql-docker-container:
    image: mysql:latest
    container_name: book-docker-sql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ebookshop
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=xxxx
    volumes:
      - /data/mysql
      
  book-service-container:
    image: springdemo/book-service
    build: book-service
    depends_on:
      - mysql-docker-container
      - registry-container
    ports:
      - "2222:2222"
    
  web-service-container:
    image: springdemo/web-service
    build: web-service
    depends_on:
      - book-service-container
      - registry-container
    ports:
      - "3333:3333"
  
  gateway-container:
    image: springdemo/gateway
    build: gateway
    depends_on:
      - registry-container
    ports:
      - "4444:4444"
      
  cassandra-docker-container:
    image: cassandra:latest
    ports:
      - "9042:9042"
    expose:
      - "9042"
    volumes:
      - /data/cassandra

  weather-service-container:
    image: springdemo/weather-service
    build: weather-service
    depends_on:
      - cassandra-docker-container
      - registry-container
    ports:
      - "5555:5555"
    volumes:
      - /data/weather-service-msapp
    restart: always

  redis-docker-container:
    image: redis:latest
    ports:
      - "6379:6379"
    expose:
      - "6379"
    volumes:
      - /data/redis

  voting-service-container:
    image: springdemo/voting-service
    build: voting-service
    depends_on:
      - redis-docker-container
      - registry-container
    ports:
      - "6666:6666"
    volumes:
      - /data/voting-service-msapp
