# Readme

. Generate Spring Boot project using Spring Initializr.
. Declare project as parent project by changing `packaging` in `pom.xml` to `pom` (instead of `jar`).
. Add a Eureka service registry. 
+
A service registry is a database that stores the instances and locations of services. Service instances register themselves with the registry. Clients/routers that need access to a service then query the registry to find an available instance.footnote:[https://microservices.io/patterns/service-registry.html] This way, we need not hard code the IP addresses of different services and can use services with dynamically assigned IP addresses (e.g. cloud platforms for autoscaling)footnote:[http://javaonfly.blogspot.com/2017/07/microservicespring-cloud-eureka-server.html]. Eureka also provides mid-tier load balancing.
+
.. Create new Maven module project `registration` with `spring-boot-starter-parent` as the parent.
.. Add `registration` as a module to the parent pom.
.. Add https://www.baeldung.com/spring-cloud-netflix-eureka[relevant dependencies] and Spring Boot Maven Plugin to registration's `pom.xml`.
.. Add `ServiceRegistrationServer` and `registration-server.yml` as per https://spring.io/blog/2015/07/14/microservices-with-spring[tutorial].
.. Compile with maven and check that it runs at `http://localhost:1111`.
. Add a microservice, `books-service`.
.. Create Maven module project and update parent POM.
.. Add https://spring.io/guides/gs/service-registration-and-discovery/[relevant dependencies].
.. Add `BooksServer.java` and config file `books-server.yml`. In `books-server.yml`, configure to use IP address instead of hostname. (Eureka's generated hostnames use underscores, which Java does not allow.)
+
[source,xml]
----
instance:
  preferIpAddress: true
----
+
.. Run `registry`, then `books-service`. Check that `books-service` is listed under Applications in `http://localhost:1111`, with details listed in `http://localhost:1111/eureka/apps/books-service`.
. Add more microservices as necessary. See below for communication between microservices.
. Add an API Gateway using Spring Cloud Gateway.
+
An API Gateway serves as a single entry point for client calls by routing requests to the appropriate microservices. Using an API Gateway reduces coupling between clients and microservices, decreases number of (client-server) round trips required, and simplifies handling of cross-cutting concerns like authorization. Read https://microservices.io/patterns/apigateway.html[these] https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/architect-microservice-container-applications/direct-client-to-microservice-communication-versus-the-api-gateway-pattern[articles] to find out more.
+
We use Spring Cloud Gateway instead of Zuul for this project so that we can support the reactive stack footnote:[https://stackoverflow.com/a/47094859].
+
.. Create a service (`pom.xml`, `Application.java` with Eureka, config file).
.. Add routing info in Java or ym. See https://github.com/spencergibb/monolith-to-microservices[sample project].
. Add Docker for easier deployment.

## Communication between microservices

### Using `RestTemplate` with Ribbon

Microservices can communicate in various ways. The most basic way is through Spring's `RestTemplate` annotated with `@LoadBalanced`, so that the `RestTemplate` uses a `RibbonLoadBalancerClient` for interactions. This way, logical hosts (e.g. `BOOKS-SERVICE`) are automatically resolved to the actual hosts. footnote:[https://stackoverflow.com/a/43022727] See https://spring.io/blog/2015/07/14/microservices-with-spring[this tutorial] for an example.

### Using Feign

Another method is using Feign, which abstracts away the REST API details. Given a microservice, we create an interface for each microservice it calls annotated with `@FeignClient` with the name (`spring.application.name`) of the microservice to be called. Declare the endpoints to be used within the interface. Finally, add `@EnableFeignClients` to the main class. Instead of calling the microservices via `RestTemplate`, we can now call the methods listed in the interface (which are implemented by Feign). See https://piotrminkowski.wordpress.com/2018/04/26/quick-guide-to-microservices-with-spring-boot-2-0-eureka-and-spring-cloud/[this article] for an example.

## Database

### Cassandra

Resources:

* https://web.archive.org/web/20100426172209/http://arin.me/blog/wtf-is-a-supercolumn-cassandra-data-model[Data modeling] (outdated terminology)
* https://wiki.apache.org/cassandra/DataModel[Resources] for learning data modeling
* https://stackoverflow.com/questions/24949676/difference-between-partition-key-composite-key-and-clustering-key-in-cassandra[Types of keys]

#### Adding Cassandra

. Add the following dependency to `pom.xml`:
+
[source, xml]
----
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-data-cassandra-reactive</artifactId>
</dependency>
----
+
. Create the entities, annotating `@Table` and the primary keys.
. Create the repository, extending a reactive repository.
. Add configuration details to yml file.
. Add configuration by extending `AbstractCassandraConfiguration`.
** To automatically create keyspace, follow https://lankydanblog.com/2017/12/03/startup-and-shutdown-scripts-in-spring-data-cassandra/[this tutorial].
** To automatically create tables, use
+
[source, java]
----
@Override
public SchemaAction getSchemaAction() {
	return SchemaAction.CREATE_IF_NOT_EXISTS;
}
----
** If your entity classes are in a different package from that of your config class, override `getEntityBasePackages()` to return the packages containing entities annotated with `@Table`. This way, Spring knows which packages to scan.

[NOTE]
====
When using Cassandra with Eureka, we need to also add `metrics-core` from `io.dropwizard.metrics` as a dependencyfootnote:[https://stackoverflow.com/a/53465934].
Otherwise, we get the error message:

____
UnsatisfiedDependencyException: Error creating bean with name 'reactiveCassandraTemplate' defined in class path resource ...
____
====

[NOTE]
====
When using Cassandra with Docker compose,

* Set `restart: always` for the service that uses  Cassandra in `docker-compose.yml`.
* Override `getContactPoints()` in the config class if using different contact points for different profiles (e.g. in docker vs locally).
====

## Deploying 

### Running manually

Run mvn spring-boot:run for each of the projects

. registry
. book-service
. web-service
. gateway

### Using Dockerfile

. run mysql container
+
[source]
----
docker run -d \
    --name demo-mysql \
    -e MYSQL_ROOT_PASSWORD=p4SSW0rd \
    -e MYSQL_DATABASE=demo \
    -e MYSQL_USER=dbuser \
    -e MYSQL_PASSWORD=dbp4ss \
    mysql:latest
----
+
. create docker image
+
[source]
----
mvn clean package dockerfile:build
----
+
. run docker image linked to mysql container
+
[source]
----
docker run -it \
    --name book-service-dbuild \
    --link demo-mysql:mysql-docker-container \
    -p 2222:2222 \
    springdemo/book-service
----

### Using Docker-compose

In main project,

. Run `mvn clean install`.
. Run `docker-compose up`.