# Spring properties
spring:
  application:
     name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    preferIpAddress: true

# HTTP Server
server:
  port: 4444   # HTTP (Tomcat) port
