server:
  port: 4444   # HTTP (Tomcat) port

spring:
  application:
     name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    preferIpAddress: true

    
---
spring:
  profiles: docker
  application:
     name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://registry-container:1111/eureka/
  instance:
    preferIpAddress: true
