server:
  port: 6666   # HTTP (Tomcat) port

spring:
  application:
    name: voting-service
  data:
    redis:
      contactPoints: localhost
      port: 6379

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    preferIpAddress: true

---
spring:
  profiles: docker
  application:
    name: voting-service
  data:
    redis:
      contactPoints: redis-docker-container
      port: 6379

eureka:
  client:
    serviceUrl:
      defaultZone: http://registry-container:1111/eureka/
  instance:
    preferIpAddress: true
