version: '3'

services:
  mysql-docker-container:
    image: mysql:latest
    container_name: book-docker-sql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ebookshop
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=xxxx
    volumes:
      - /data/mysql
  book-service-container:
    image: springdemo/book-service
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-docker-container
    ports:
      - 2222:2222
    volumes:
      - /data/book-service-msapp